Feat/scrum 42 network module implementation
project-lyrics/app-iOS pull request #3
Opened 2024-04-05 13:01 UTC by derrickkim0109

## PR 타입
어떤 변경에 대한 PR인가요?

- [ ] 버그 수정
- [x] Feature / 신기능
- [ ] 코드 스타일 업데이트 (formatting, local variables)
- [ ] 리팩토링 (no functional changes, no api changes)
- [ ] 빌드 관련 변경사항
- [ ] CI 관련된 변경사항
- [ ] Documentation content changes
- [ ] 구조 변경
- [ ] Other... 추가 설명 요망:
## 배경

- Network Module 구현이 필요함
## 목표

- Combine으로 Network Module 구현
- Sample API를 통해 Network Module 테스트
## 결과 (Optional)

## Trouble or Trouble Shooting(Optional)

2024-04-05 13:10 UTC, derrickkim0109 reviewed
수정이 필요한 부분 코멘트 남겨주세요..ㅎㅎ

2024-04-05 13:10 UTC, derrickkim0109 commented on Projects/Core/Network/Project.swift
> +                .shared(implements: .Util)
Publisher 등의 익스텐션을 사용하기 위해 Util 모듈을 디펜던시에 추가했습니다.

2024-04-05 13:10 UTC, derrickkim0109 commented on Projects/Core/Network/Sources/API/FeelinAPI.swift
> +extension FeelinAPI: HTTPNetworking {
API Controller 별로 각 case를 추가하기 위해 Sample API 를 만들었습니다.

2024-04-05 13:10 UTC, derrickkim0109 commented on Projects/Feature/Sources/FeatureExport.swift
> +@_exported import FeatureOnboarding
이렇게 Export 파일을 추가한 이유는 해당 모듈에 하위 모듈을 외부에서 사용하기 위해 설정합니다.

2024-04-06 12:08 UTC, inwoodev requested changes
고생하셨어요, 덕분에 오늘도 tuist모듈화에 대해서 하나 더 알아갑니다 ㅎㅎ. 몇 자 남겨 봤습니다. 혹시나 추가적인 설명이 필요한 부분이 있다면 언제든 연락 주세요~~

2024-04-06 12:08 UTC, inwoodev commented on Projects/Core/Network/Interface/Sources/NetworkProviderInterface.swift
> +}
해당 프로토콜을 채택해야 하는 타입을 참조타입으로 제한해야 한다면, AnyObject 프로토콜을 상속 받는것도 고려 해 볼 수 있을 것 같은데 어떻게 생각하시나요?

2024-04-06 12:08 UTC, inwoodev commented on Projects/Core/Network/Sources/NetworkProvider.swift
> +
NetworkProvider가 참조타입이어야 할 것 같긴하네요. 가령 `URLSessionDelegate`를 채택하여 urlSession을 활용한 통신구현을  필요시 delegate방식으로도 구현할 수 있겠네요~👍👍

2024-04-06 12:08 UTC, inwoodev commented on Projects/Core/Network/Sources/NetworkProvider.swift
> +                .eraseToAnyPublisher()
`.receive(on: DispatchQueue.main)` 다운스트림이 메인쓰레드에서 작업을 전달받는 부분을 NetworkProvider에서 하도록 해당 시점에서 체이닝해야 하는 이유가 있을까요?~👀

2024-04-06 12:08 UTC, inwoodev commented on Projects/Shared/Util/Interface/Sources/Errors/NetworkError.swift
> +    case authorizationError
결국 4xx 5xx에 포함되는 케이스들이라고 생각이 들어서 굳이 별도의 case로 나눠야 할까 하는 생각이 들었어요. 데릭은 어떻게 생각하시나요~?

2024-04-06 12:08 UTC, inwoodev commented on Projects/Core/Network/Sources/NetworkProvider.swift
> +            }
URLRequestError핸들링도 필요할 것 같아요!

2024-04-06 12:08 UTC, inwoodev commented on Projects/Feature/Sources/FeatureExport.swift
> +@_exported import FeatureOnboarding
하나 더 배워갑니다~👏👏👏

2024-04-06 12:08 UTC, inwoodev commented on Projects/Core/Network/Tests/Sources/SampleAPITests.swift
> +            .store(in: &cancellables)
여기서 테스트하고자 하는 sut(system under test)가 Mock객체인게 조금 이상한 것 같아요!. 음 제 생각에는 이 NetworkProvider를 테스트 하시고자 한다면 MockURLSession을 주입하여 테스트하는게 맞다고 생각이 듭니다!!

2024-04-06 13:04 UTC, derrickkim0109 commented on Projects/Core/Network/Interface/Sources/NetworkProviderInterface.swift
> +}
좋은 것 같습니다. 바로 적용하겠습니다:)

2024-04-06 13:09 UTC, derrickkim0109 commented on Projects/Core/Network/Sources/NetworkProvider.swift
> +
URLSessionDelegate를 채택한 상황에 대해서 설명해주실 수 있을까요?

2024-04-06 13:11 UTC, derrickkim0109 commented on Projects/Shared/Util/Interface/Sources/Errors/NetworkError.swift
> +    case authorizationError
맞습니다. 해당 케이스들은 필요할 때 추가하는 걸로 정하면 좋을 것 같네요.

2024-04-06 13:22 UTC, derrickkim0109 commented on Projects/Core/Network/Sources/NetworkProvider.swift
> +            }
```swift 
NetworkError.urlRequestError(.bodyEncodingError)
```

NetworkError 타입으로 보낼 수 있도록 수정했습니다!

2024-04-06 13:24 UTC, derrickkim0109 commented on Projects/Core/Network/Sources/NetworkProvider.swift
> +                .eraseToAnyPublisher()
Response로 받는 데이터로 UI를 업데이트하는 경우가 많다고 생각해서 Main Thread로 설정했어요.
코드 흐름 상 이상할까요?

2024-04-06 13:26 UTC, derrickkim0109 commented on Projects/Core/Network/Tests/Sources/SampleAPITests.swift
> +            .store(in: &cancellables)
아하..! 이해했습니다. 다시 수정해보겠습니다!

2024-04-06 13:40 UTC, derrickkim0109 commented on Projects/Core/Network/Sources/NetworkProvider.swift
> +                .eraseToAnyPublisher()
불필요한 거 같아서.. 수정했습니다..ㅎㅎ

2024-04-06 14:01 UTC, derrickkim0109 commented on Projects/Core/Network/Tests/Sources/SampleAPITests.swift
> +            .store(in: &cancellables)
https://seob-p.tistory.com/18

2024-04-06 14:39 UTC, inwoodev commented on Projects/Core/Network/Sources/NetworkProvider.swift
> +
urlSession자체의 dataTask를 통해서 네트워크 호출을 할 수도 있지만 NetworkProvider가 URLSession의 대리자가 되어서 네트워크 작업을 대신할 수도 있죠. 그런 경우에는 URLSessionDelegate를 채택하기 위해서는 class타입이어야 하니까 NetworkProvider가 참조타입인게 맞다는 맥락으로 드린 말씀이었습니다 :)

2024-04-06 14:41 UTC, inwoodev commented on Projects/Core/Network/Sources/NetworkProvider.swift
> +                .eraseToAnyPublisher()
허들로도 말씀 드렸긴 하지만 네트워크로부터 받는 데이터를 UI에 적용하지 않는 케이스를 회사 생활을 통해서 경험해봐서요. 네트워크 레이어에서 굳이 메인쓰레드로 보내는 제약을 둘 필요 없다는 뜻이었습니다 :)

2024-04-06 14:45 UTC, inwoodev commented on Projects/Shared/Util/Interface/Sources/Errors/NetworkError.swift
> +    case unknownError
케이스 파라미터를 통해 옵셔널 스트링을 받는 것도 좋다고 생각합니다!!

2024-04-10 13:59 UTC, inwoodev reviewed
슬슬 머지해도 괜찮을 것 같은데요? 테스트 케이스를 혹시나 더 추가하시거나 수정을 더 하시기 원하신다면 일단 머지는 보류하도록 하겠습니다~ 의견 편하게 주세요, 데릭!! :)

고생하셨습니다~!!

2024-04-10 13:59 UTC, inwoodev commented on Projects/Core/Network/Interface/Sources/Error/NetworkError.swift
> +        case unavailableForLegalReasons = 451
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#client_error_responses

요 링크 참고 했을 때 407, 423과 같은 케이스들이 누락된거 같은데 확인 가능하실까요~?

2024-04-10 13:59 UTC, inwoodev commented on Projects/Core/Network/Sources/EndPoint/HTTPRequestConfiguring.swift
>  extension HTTPRequestConfiguring {
extension의 모든 메서드 들이 private인 경우 요렇게 extension 자체를 private하게 선언 해 볼 수도 있을 듯 합니다 :)
``` swift
private extension HTTPRequestConfiguring {
.
.
.
}
```

2024-04-10 13:59 UTC, inwoodev commented on Projects/Core/Network/Testing/Sources/MockURLProtocol.swift
> +}
URLProtocol을 활용해서 Mock객체를 만드셨군요!! 👏👏👏

다만 Combine을 여기서까지 사용해야 하는 이유를 저는 잘 모르겠어요😅 . 데릭의 생각이 궁금합니다~~ :)

2024-04-10 13:59 UTC, inwoodev commented on Projects/Core/Network/Tests/Sources/NetworkProviderTests.swift
> +        }
위 코멘트랑 이어지는 질문입니다. 제가 아직 부족해서 그런지 몰라도 해당 클로저 내부에서 퍼블리셔를 리턴해서 얻는 이점이 뭔지 잘 모르겠어요 ㅠ. 제가 놓치고 있는게 있을까요? 만약 있다면 가르침을 🙏!!! 😁
제 개인적인 생각으로는 아래와 같이 구현해도 충분하지 않나 싶긴 하거든요...

``` swift
MockURLProtocol.requestHandler = { request in
     let mockResponse = HTTPURLResponse(
                url: request.url!,
                statusCode: 200,
                httpVersion: nil,
                headerFields: nil
            )!
      return (mockResponse, mockData)
    }
```

2024-04-10 13:59 UTC, inwoodev commented on Projects/Core/Network/Sources/NetworkProvider.swift
> +    public init(session: URLSession = URLSession.shared) {
요런 섬세한 캐치 👏👏👏👏

2024-04-10 13:59 UTC, inwoodev commented on Projects/Core/Network/Sources/Extensions/Publisher+.swift
> +                )
예외처리할 때 .badRequestError 또는 .internalServerError말고 약간 .4xxError(statusCode: Int)와 같은 케이스를 하나 추가해서 해당 에러를 리턴하는 건 어떨까요? 그리고 description에는 ClientError has occured status code: \(statusCode)와 같은 식으로 처리를 하게 된다면 400번대 500번대에서 저희가 실수로 누락했거나 예상치 못했던 케이스 또한 잡아 낼 수 있을 것 같아서요!!

``` swift
case 400..<451:
  throw NetworkError.clientError(
    NetworkError.ClientError(rawValue: response.statusCode) ?? .4xxError(statusCode: response.statusCode)
)
```

2024-04-10 15:50 UTC, derrickkim0109 commented on Projects/Core/Network/Testing/Sources/MockURLProtocol.swift
> +}
아 이 부분은 저번에 허들로 얘기했을 때, URLProtocol 테스트 코드에서 Combine을 사용해서 적용하자는 말이 이 부분에도 적용되는 걸로 잘못 생각했네요.ㅎㅎ 불필요한 것 같아서 수정하도록 하겠습니다.

2024-04-10 15:50 UTC, derrickkim0109 commented on Projects/Core/Network/Tests/Sources/NetworkProviderTests.swift
> +        }
동의합니다. 수정할게요.ㅎ

2024-04-10 23:00 UTC, derrickkim0109 commented on Projects/Core/Network/Sources/Extensions/Publisher+.swift
> +                )
지금 구조가 Client, Server enum의 케이스가 Int로 설정되어 있어서 statusCode를 받는 것은 어려울 것 같습니다. 또한, 네이밍에서 숫자가 먼저 입력되는 것은 적용할 수 없는 것으로 컴파일러가 알려주고 있습니다. 

지금 코드는 400번, 500번대 에러를 모두 체크하는 상황이라 그 외의 에러는 `case unknownError( _ description: String)`에서 status Code를 받을 수 있는 상황입니다. 또한, 저희가 설정하지 않아 400번대에 없는 4xx Code의 경우, 굉장히 특이한 케이스이지 않을까요..? 그리고 [HTTP Error](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#client_error_responses)이 사이트를 토대로 작성한 에러 케이스 였는데 만약, 그 외의 케이스가 나온다면 어떤 케이스인지 정의가 가능할까요?

예상치 못했던 케이스가 바로 unknownError로 생각하면 되지 않을까요?
어떻게 생각하세요?

2024-04-11 03:17 UTC, inwoodev commented on Projects/Core/Network/Sources/Extensions/Publisher+.swift
> +                )
아하 제가 rawValue인걸 놓치고 있었네요~ 네네 그럼 이대로 진행하시죠~~~

2024-04-11 11:50 UTC, inwoodev commented on Projects/Core/Network/Testing/Sources/MockURLProtocol.swift
> +}
오 뭔가 착오가 있었던것 같긴하네요. 컴바인 얘기를 제가 꺼냈다니!! ㅎㅎ 근데 뭐 일단 이렇게 구현해도 크게 문제가 될거 같지는 않네용!!🙌🙌

2024-04-11 11:50 UTC, merged