Feat/Scrum 131 회원가입 도메인 & 프레젠테이션 로직 구현
project-lyrics/app-iOS pull request #36
Opened 2024-07-07 15:06 UTC by derrickkim0109

## PR 타입
어떤 변경에 대한 PR인가요?

- [ ] 버그 수정
- [x] Feature / 신기능
- [ ] 코드 스타일 업데이트 (formatting, local variables)
- [ ] 리팩토링 (no functional changes, no api changes)
- [ ] 빌드 관련 변경사항
- [ ] CI 관련된 변경사항
- [ ] Documentation content changes
- [ ] 구조 변경
- [ ] Other... 추가 설명 요망:

## 배경

- 온보딩 flow에서 있는 각 뷰의 인터렉션이 정상 작동하도록 만들어야 합니다.

## 목표

- 약관 동의 화면에서 각 동의가 클릭 될 시 전체 동의도 클릭되고 다음 버튼 활성화
- 성별 및 출생년 선택 시 다음 버튼 활성화
- 프로필 텍스트 입력 시 다음 버튼 활성화

## 결과 (Optional)

- 각 인터렉션에 맞게 다음 버튼이 활성화 되고 다음 화면으로 넘어갈 수 있도록 coordinator에서 각 메서드를 통해 처리됩니다.

## Trouble or Trouble Shooting(Optional)

2024-07-07 23:28 UTC, derrickkim0109 reviewed
추가적으로 수정이 필요한 부분 말씀해주시면 감사하겠습니다~!

2024-07-07 23:28 UTC, derrickkim0109 commented on Projects/Coordinator/Main/Interface/Sources/MainInterface.swift
> -        navigationController.pushViewController(viewController, animated: false)
사용하지 않는 코드라 제거했습니다.

2024-07-07 23:28 UTC, derrickkim0109 commented on Projects/Core/Network/Interface/Sources/DTO/UserSignUpRequest.swift
> +    }
사용처에서 initializer를 사용해야 해서 구현했습니다.

2024-07-07 23:28 UTC, derrickkim0109 commented on Projects/Domain/OAuth/Interface/Sources/Model/UserSignUpEntity.swift
> +    }
논의한 대로 Onboarding 화면 별로 나눠서 데이터를 이동시켜야 해서 Optional로 수정했습니다~!

2024-07-07 23:28 UTC, derrickkim0109 commented on Projects/Feature/Onboarding/Interface/Sources/Components/Profile/ProfileView.swift
> +
NavigationBar 뷰에 백버튼을 주입하는 방식으로 구현했습니다.

2024-07-07 23:28 UTC, derrickkim0109 commented on Projects/Feature/Onboarding/Interface/Sources/Components/Profile/ProfileView.swift
> +    lazy var nicknameTextField = FeelinLineInputField(placeholder: "닉네임")
해당 Custom TextField의 TextField에 접근하기 위해 internal로 변경했습니다.

2024-07-07 23:28 UTC, derrickkim0109 commented on Projects/Feature/Onboarding/Interface/Sources/Components/UserAgreement/CheckBoxButton.swift
> +
isChecked를 기존에 있는 프로퍼티인 isSelected로 대체했습니다.

2024-07-07 23:28 UTC, derrickkim0109 commented on Projects/Feature/Onboarding/Interface/Sources/Components/UserAgreement/UserAgreementListView.swift
> +            self?.allAgreeLabel.textColor = button.state == .selected ? Colors.alertSuccess : Colors.gray04
기존 코드를 삼항연산자로 대체했습니다.

2024-07-07 23:28 UTC, derrickkim0109 commented on Projects/Feature/Onboarding/Interface/Sources/Components/UserAgreement/UserAgreementListView.swift
> +
title, agreement에 대한 부분은 따로 관리가 필요하다고 생각해서 TermEntity를 구현해 각 title의 내용을 관리할 수 있도록 구현했습니다.

2024-07-07 23:28 UTC, derrickkim0109 commented on Projects/Feature/Onboarding/Interface/Sources/Components/UserInformationView.swift
> +    }()
navigationBar에 backButton과 skipButton을 넣습니다.

2024-07-07 23:28 UTC, derrickkim0109 commented on Projects/Feature/Onboarding/Interface/Sources/Components/UserInformationView.swift
> +                .marginTop(28)
네비게이션 바의 추가 구현으로 해당 값을 수정했ㅅ브니다.

2024-07-07 23:28 UTC, derrickkim0109 commented on Projects/Feature/Onboarding/Interface/Sources/ViewControllers/EditProfileViewController.swift
> +            .store(in: &cancellables)
collectionView도 combine cocoa가 될 수 있도록 변경했습니다.

2024-07-07 23:28 UTC, derrickkim0109 commented on Projects/Shared/DesignSystem/Sources/Views/FeelinLineInputField.swift
> +    }
잘못 작성된 텍스트라면 다음 버튼이 활성화되지 않도록 하기 위해 해당 프로퍼티를 추가했습니다.

2024-08-04 23:07 UTC, derrickkim0109 commented
- Auto Login에 필요한 Response 객체 추가
- ProfileViewController Input, Output 구조 변경
- Sign up 비지니스 로직 추가

2024-08-12 13:52 UTC, inwoodev requested changes
고생하셨습니다. 몇 가지 코멘트 확인 요청드려요~

2024-08-12 13:52 UTC, inwoodev commented on Projects/Shared/DesignSystem/Sources/Views/NavigationBar.swift
> +}
고생하셨습니다~ 요긴하게 사용하겠네요~!!

2024-08-12 13:52 UTC, inwoodev commented on Projects/Coordinator/Onboarding/Interface/Sources/OnboardingInterface.swift
> +
네비게이션 같은 경우 show동사를 활용하는걸까요?
그렇다면 modal 같은 경우 어떤 동사를 활용해 볼 수 있을까요~?

2024-08-12 13:52 UTC, inwoodev commented on Projects/Shared/Util/Sources/Extensions/UICollectionView+.swift
> +}
lgtm~~👍👍👍

2024-08-12 13:52 UTC, inwoodev commented on Projects/Feature/Onboarding/Interface/Sources/Components/UserAgreement/CheckBoxButton.swift
> +
맞습니다~ isChecked는 불필요한 값이었어요 ㅎㅎ

2024-08-12 13:52 UTC, inwoodev commented on Projects/Core/Network/Tests/Sources/NetworkProviderTests.swift
> +            """.data(using: .utf8)!
태현님, 요거 모델 수정해야할듯 해요!! 저희 status는 안받기로 합의된걸로 기억합니당~

2024-08-12 13:52 UTC, inwoodev commented on Projects/DependencyInjection/Sources/DIContainer/DIContainer.swift
> +}
요렇게 가시죠~ 저도 수정하겠습니다~

2024-08-12 13:52 UTC, inwoodev commented on Projects/Domain/OAuth/Sources/Service/UserValidityService.swift
>  import DomainOAuthInterface
Core가 있다면 CoreNetworkInterface는 굳이 import 안 해도 될듯 해요~

2024-08-12 13:52 UTC, inwoodev commented on Projects/Feature/Onboarding/Interface/Sources/ViewControllers/ProfileViewController.swift
> +                self.present(self.editProfileViewController, animated: false)
`guard let self = self else { return }` 구문이 굳이 필요하지 않은 듯 해요~ p4

2024-08-12 13:52 UTC, inwoodev commented on Projects/Feature/Onboarding/Interface/Sources/ViewControllers/ProfileViewController.swift
> +            .share()
`.share()`가 어떤 측면에서 필요할까요~? p5

2024-08-12 13:52 UTC, inwoodev commented on Projects/Feature/Onboarding/Interface/Sources/ViewControllers/ProfileViewController.swift
>          )
디코로 말씀드린거 같이 하나의 publisher를 input에 주입하는 방향으로 수정하셔도 좋을 듯 해요~ p3

2024-08-12 13:52 UTC, inwoodev commented on Projects/Feature/Onboarding/Interface/Sources/ViewModel/ProfileViewModel.swift
> +    }
요거 image는 optional이어도 될듯 한데 어떻게 생각하시나요~ p3

2024-08-12 13:52 UTC, inwoodev commented on Projects/Feature/Onboarding/Interface/Sources/ViewModel/ProfileViewModel.swift
> +            .eraseToAnyPublisher()
compactMap을 통해 optional한 값이 방출되는게 조금 마음에 걸립니다...ㅎ

2024-08-12 13:52 UTC, inwoodev commented on Projects/Feature/Onboarding/Interface/Sources/ViewModel/ProfileViewModel.swift
>              .eraseToAnyPublisher()
CombineLatest 중첩인데 작동 잘 되는지 확인 요청 드려요~ p2

2024-08-12 13:52 UTC, inwoodev commented on Projects/Feature/Onboarding/Interface/Sources/ViewModel/ProfileViewModel.swift
> +    private var profileImageErrorPublisher = PassthroughSubject<String, Never>()
profileImageErrorPublisher가 꼭 필요한가 싶기는 합니다. api콜을 통해서 이미지를 가져오지 않기도 하고 이미지 갯수가 많은 것도 아니어서요~! p4

2024-08-15 02:14 UTC, derrickkim0109 commented on Projects/Coordinator/Onboarding/Interface/Sources/OnboardingInterface.swift
> +
이 부분은 push~로 변경되어있습니다.

2024-08-15 02:21 UTC, derrickkim0109 commented on Projects/Core/Network/Tests/Sources/NetworkProviderTests.swift
> +            """.data(using: .utf8)!
수정했습니다.

2024-08-15 02:22 UTC, derrickkim0109 commented on Projects/Domain/OAuth/Sources/Service/UserValidityService.swift
>  import DomainOAuthInterface
수정했습니다~

2024-08-15 02:23 UTC, derrickkim0109 commented on Projects/Feature/Onboarding/Interface/Sources/ViewControllers/ProfileViewController.swift
> +                self.present(self.editProfileViewController, animated: false)
수정했습니다~

2024-08-15 02:23 UTC, derrickkim0109 commented on Projects/Feature/Onboarding/Interface/Sources/ViewControllers/ProfileViewController.swift
> +            .share()
불필요해서 제거했습니다~!

2024-08-15 02:23 UTC, derrickkim0109 commented on Projects/Feature/Onboarding/Interface/Sources/ViewControllers/ProfileViewController.swift
>          )
수정했습니다~!

2024-08-15 02:23 UTC, derrickkim0109 commented on Projects/Feature/Onboarding/Interface/Sources/ViewModel/ProfileViewModel.swift
> +    }
좋습니다~! 수정했습니다.

2024-08-15 02:41 UTC, derrickkim0109 commented on Projects/Feature/Onboarding/Interface/Sources/ViewModel/ProfileViewModel.swift
> +            .eraseToAnyPublisher()
수정했습니다.

2024-08-15 02:43 UTC, derrickkim0109 commented on Projects/Feature/Onboarding/Interface/Sources/ViewModel/ProfileViewModel.swift
>              .eraseToAnyPublisher()
확인 결과 잘 작동합니다. zip으로 변경 시 nickname을 최신 값으로 가져올 수 없어 combineLatest 중첩이 필요합니다.

2024-08-15 02:43 UTC, derrickkim0109 commented on Projects/Feature/Onboarding/Interface/Sources/ViewModel/ProfileViewModel.swift
> +    private var profileImageErrorPublisher = PassthroughSubject<String, Never>()
제거했습니다.

2024-08-15 03:11 UTC, inwoodev commented on Projects/Feature/Onboarding/Interface/Sources/ViewModel/ProfileViewModel.swift
>              .eraseToAnyPublisher()
아닙니다~~ 확인차 코멘트 드린거에요. 잘 작동한다면 굳이 다른 방법을 찾지 않아도 될듯 합니다~

2024-08-15 03:19 UTC, inwoodev commented on Projects/Coordinator/Onboarding/Interface/Sources/OnboardingInterface.swift
> +
👍👍

2024-08-15 03:20 UTC, inwoodev approved these changes
확인했습니다~ input & output로직도 공들이신만큼 개선되어보입니다. 머지하셔도 좋습니다~ 얼른 다음 feature로 넘어가시죠

2024-08-15 03:21 UTC, merged