QA-0.01 온보딩 약관동의 화면 에러 및 회원탈퇴 Response, 로그인 화면 말풍선 수정
project-lyrics/app-iOS pull request #80
Opened 2024-10-22 13:46 UTC by derrickkim0109

## PR 타입
어떤 변경에 대한 PR인가요?

- [x] 버그 수정
- [ ] Feature / 신기능
- [ ] 코드 스타일 업데이트 (formatting, local variables)
- [ ] 리팩토링 (no functional changes, no api changes)
- [ ] 빌드 관련 변경사항
- [ ] CI 관련된 변경사항
- [ ] Documentation content changes
- [ ] 구조 변경
- [ ] Other... 추가 설명 요망:

## 배경

- 온보딩 Flow의 약관동의 화면에서 전체 동의 선택 > 다른 동의 체크 박스 선택 시 `시작하기` 버튼이 해제되지 않는 버그
- `마지막에 로그인했어요` 말풍선 아래 뽀족한 부분 border 다크모드 대응되지 않았음
- 회원탈퇴 Response 프로퍼티 이름 변경됨

## 목표

- 약관동의 체크박스가 해제되면 시작하기 버튼이 비활성화 되도록 해야함
- border 컬러가 통일되야 함
- 회원탈퇴가 되어야함

## 결과 (Optional)

| 다크모드에서 말풍선 색이 통일 | 약관동의| 회원탈퇴|
|--|--|--|
|<img src="https://github.com/user-attachments/assets/e650f429-e03e-4147-8809-e7272ccc3749" width="250">|<img src="https://github.com/user-attachments/assets/f69b55c7-d505-4f72-990c-50cdf2920b61" width="250">|<img src="https://github.com/user-attachments/assets/69f9de11-31e2-4398-a9d2-1789c8fbb651" width="250">|

2024-10-23 01:23 UTC, inwoodev requested changes
고생하셨습니다~ 이전 pr커밋이 추가되지 않은듯 한데 요 부분 확인 해 주시면 좋을 듯 합니다~ 그리고 코멘트 남겼어요. 확인 해 주세요~

2024-10-23 01:23 UTC, inwoodev commented on Projects/Core/Network/Interface/Sources/DTO/Response/FeelinDefaultResponse.swift
확인했습니다~

2024-10-23 01:23 UTC, inwoodev commented on Projects/Feature/Onboarding/Interface/Sources/ViewControllers/ProfileViewController.swift
>              .eraseToAnyPublisher()
태현님, 혹시 에러가 발생하면  coordinator를 통해서 화면전환이 되지 않는 부분도 테스트되셨을 까요?

그리고 @jcrescent61 이 첨부해 주신 gif를 확인 했을 때 에러 메세지 또한 정상적으로 출력되지 않는 듯 합니다.

그래서 제가 드리고 싶은 의견은
1. `SignUpError` 모델 수정(FeelinError 메세지를 출력할 수 있게. 자세한 건 다른 에러들 참고하시면 좋을 듯 합니다)
2. 에러 발생 시 화면 이동 방지
3. 그리고 throttle 대신에 `switchToLatest`가 이 상황에서는 더 요긴하게 중복 네트워크 콜 호출을 방지할 수 있지 않나 싶습니다!
p3

2024-10-23 12:47 UTC, derrickkim0109 commented on Projects/Feature/Onboarding/Interface/Sources/ViewControllers/ProfileViewController.swift
>              .eraseToAnyPublisher()
넵 알겠습니다~!

2024-10-23 13:18 UTC, derrickkim0109 commented on Projects/Feature/Onboarding/Interface/Sources/ViewControllers/ProfileViewController.swift
>              .eraseToAnyPublisher()
1. SignUpError의 message를 추가했습니다.
2. 이 부분은 이미 이동을 방지하고 있습니다.
3. 엘렌이 해주신 QA는 여러 번 시작하기를 호출한 상태에서 발생할 수 있는 문제로 이해했는데 제가 잘못 본 걸까요? 제 생각에는 2번이 가능했던 이유는 여러 번 API를 호출해서 발생한 문제라고 생각합니다. 

처음에 회원가입 API 호출을 한 상태에서 또 다시 SignUp API를 호출하여 두 번째 API 호출로 받은 Response는 Error를 방출하여 Alert 에러 메세지를 받은 상황으로 이해했습니다.
그래서 제 생각에는 switchToLatest 처리는 지금 상황과는 맞지않은 대처라고 생각이 드는데 어떻게 생각하시나요? 

음.. 제 생각에는 switchToLatest는 가장 마지막에 방출된 Publisher를 받게 하는 기능이라고 하면, 결국 Error에서 회원가입 완료로 넘어가지 못하게 될 것 같습니다.
그래서 throttle로 처음에 호출한 API를 2초동안 기다리도록 하는 것으로 처리해봤습니다. 

제가 이해한게 맞을까요?

2024-10-23 13:21 UTC, derrickkim0109 commented on Projects/Feature/Onboarding/Interface/Sources/ViewControllers/ProfileViewController.swift
>              .eraseToAnyPublisher()
success를 받는 경우, nextButton의 isEnable false로 처리하는 건 어떻게 생각하세요?

2024-10-23 14:13 UTC, inwoodev commented on Projects/Feature/Onboarding/Interface/Sources/ViewControllers/ProfileViewController.swift
>              .eraseToAnyPublisher()
요 일단 throttle 부분은 제가 잘못 이해한게 맞습니다 ㅎㅎ; switchToLatest나 throttle 둘 다 사용해도 무방한듯 합니다. 혼란을 야기해서 죄송합니다 :)

2024-10-23 14:21 UTC, inwoodev commented on Projects/Feature/Onboarding/Interface/Sources/ViewControllers/ProfileViewController.swift
>              .eraseToAnyPublisher()
`success를 받는 경우, nextButton의 isEnable false로 처리하는 건 어떻게 생각하세요?` 이 의견도 좋습니다~~

2024-10-23 14:43 UTC, derrickkim0109 commented on Projects/Feature/Onboarding/Interface/Sources/ViewControllers/ProfileViewController.swift
>              .eraseToAnyPublisher()
아닙니다~ 

구두로 전달 받은대로, 현 부분은 throttle로 유지하도록 하겠습니다.

2024-10-31 12:34 UTC, derrickkim0109 commented on Projects/Feature/Home/Interface/Sources/Views/WritingNote/WritingNoteView.swift
> +    public func calculateNoteCharCountContainerHeight(
기존에 말씀드렸던 방식은 note 텍스트뷰의 라인이 변경되는 만큼 screen Height의 비율로 spacer를 설정했었습니다. 
하지만 이 방식은 처리할 수 없는 분기처리가 너무 많다는 문제가 있었습니다.

그래서 스크린 높이에 noteContainerView가 차지해야 할 부분을 제외한 나머지 부분을 빼는 방식으로 구현해봤습니다.

2024-10-31 12:34 UTC, derrickkim0109 commented on Projects/Coordinator/Home/Interface/Sources/HomeCoordinatorInterface.swift
> +        // TODO: 노트 작성 완료 후 업데이트 메서드 호출
Postnote, Editnote 완료 이후 시점입니다.

2024-10-31 12:34 UTC, derrickkim0109 commented on Projects/Feature/Home/Interface/Sources/ViewControllers/WritingNote/PostNoteViewController.swift
> +                    let additionalBottomInset: CGFloat = noSafeArea ? 33 : 0
se의 경우 safe Area bottom을 가져올 수 없어서 하드코딩했습니다.

2024-10-31 12:34 UTC, derrickkim0109 commented on Projects/Feature/Home/Interface/Sources/ViewControllers/WritingNote/PostNoteViewController.swift
> +                    let additionalBottomInset: CGFloat = noSafeArea ? 33 : 0
12는 note container 의 bottom 값입니다.

2024-10-31 12:34 UTC, derrickkim0109 commented on Projects/Feature/Home/Interface/Sources/ViewControllers/WritingNote/PostNoteViewController.swift
> +                    updateCharacterCountForLyrics()
기존에 delegate `func textView(_ textView: UITextView, shouldChangeTextIn range: NSRange, replacementText text: String) -> Bool`에 선언한 부분을 didChange로 로직을 옮겼습니다.

2024-10-31 12:34 UTC, derrickkim0109 commented on Projects/Feature/Home/Interface/Sources/Views/WritingNote/WritingNoteView.swift
> -        ])
기존에 구현할 때는 겹치도록 구현하는 방법을 생각하지 못하고 개발하여 Constraint으로 위에 뷰를 겹치는 방식을 선택했지만, 이 설정으로 flexlayout이 깨지는 문제가 있어서 flexlayout으로 변경했습니다.

2024-10-31 12:34 UTC, derrickkim0109 commented on Projects/Feature/Home/Interface/Sources/Views/WritingNote/WritingNoteView.swift
> +        addToPlayButton.setImage(FeelinImages.selectedSongActive, for: .normal)
기획, 디자인 변경으로 아이콘을 변경했습니다.

2024-10-31 14:22 UTC, inwoodev approved these changes
야근하시느라 바쁘셨을텐데...와 너무 고생하셨습니다.

머지해도 괜찮을 듯 하네요.

2024-10-31 14:22 UTC, inwoodev commented on Projects/Feature/Home/Interface/Sources/Views/WritingNote/WritingNoteView.swift
> +    }
오 괜찮은 접근인듯 합니다. 다만 추후 artistInfoHeaderViewHeight와 lyricsTextBodyViewHeight를 하드코딩하지 않는 방향으로 수정 해 볼 수 있을 듯 해요~

p5

2024-10-31 14:22 UTC, inwoodev commented on Projects/Feature/Home/Interface/Sources/ViewControllers/WritingNote/PostNoteViewController.swift
> +                    updateCharacterCountForLyrics()
현 상황에서는 이게 최선인것 같네요. 고생하셨습니다~

2024-10-31 14:23 UTC, merged