QA-0.01(5) 노트 작성 / 수정 완료 시점, 노트 삭제 시점에 맞춰 노트 리스트 업데이트
project-lyrics/app-iOS pull request #84
Opened 2024-11-11 23:13 UTC by derrickkim0109

## PR 타입
어떤 변경에 대한 PR인가요?

- [ ] 버그 수정
- [ ] Feature / 신기능
- [ ] 코드 스타일 업데이트 (formatting, local variables)
- [x] 리팩토링 (no functional changes, no api changes)
- [ ] 빌드 관련 변경사항
- [ ] CI 관련된 변경사항
- [ ] Documentation content changes
- [ ] 구조 변경
- [ ] Other... 추가 설명 요망:

## 배경

## 목표

## 결과 (Optional)

## Trouble or Trouble Shooting(Optional)

2024-11-13 07:42 UTC, inwoodev requested changes
고생하셨습니다~ 한 가지 정도만 짚고 넘어갔으면 합니다~

2024-11-13 07:42 UTC, inwoodev commented on Projects/Feature/Home/Interface/Sources/ViewControllers/HomeViewController.swift
> +                    )
태현님, 요 부분은 coordinator에게 넘기는게 맞는것 같아요~ 어떻게 생각하시나요?
p2

2024-11-13 07:42 UTC, inwoodev commented on Projects/Feature/MyPage/Interface/Sources/ViewControllers/PageControl/BookmarkViewController.swift
> +            noteDetailDataSource.apply(snapshot)
오 이렇게 하니까 실기기에서도 버벅임이 사라지신걸까요?

2024-11-13 15:27 UTC, derrickkim0109 commented on Projects/Feature/MyPage/Interface/Sources/ViewControllers/PageControl/BookmarkViewController.swift
> +            noteDetailDataSource.apply(snapshot)
네 맞습니다. 기존에 있던 드르륵 거리는 부분이 사라졌습니다.

2024-11-13 15:28 UTC, derrickkim0109 commented on Projects/Feature/Home/Interface/Sources/ViewControllers/HomeViewController.swift
> +                    )
오우.. 제가 실수했군요. 

바로 수정했습니다.

2024-11-14 01:08 UTC, inwoodev approved these changes
고생하셨습니다. 머지하겠습니다~

2024-11-14 01:08 UTC, inwoodev commented on Projects/Feature/Home/Interface/Sources/ViewControllers/HomeViewController.swift
> +                        errorData: error.data
👍👍👍

2024-11-14 01:08 UTC, merged