QA-1.0.1 레이아웃 깨지는 부분 수정, Safe Area Bottom 설정 변경, 프로필 수정 페이지 수정
project-lyrics/app-iOS pull request #89
Opened 2024-12-11 23:13 UTC by derrickkim0109

## PR 타입
어떤 변경에 대한 PR인가요?

- [ ] 버그 수정
- [ ] Feature / 신기능
- [ ] 코드 스타일 업데이트 (formatting, local variables)
- [ ] 리팩토링 (no functional changes, no api changes)
- [ ] 빌드 관련 변경사항
- [ ] CI 관련된 변경사항
- [ ] Documentation content changes
- [ ] 구조 변경
- [ ] Other... 추가 설명 요망:

## 배경

## 목표

## 결과 (Optional)

## Trouble or Trouble Shooting(Optional)

2024-12-14 00:51 UTC, inwoodev requested changes
연말인데도 고생이 많으십니다~ 몇 개 코멘트 남겨봤어요. 확인 해 주세용~

2024-12-14 00:51 UTC, inwoodev commented on Projects/Feature/Home/Interface/Sources/Views/ArtistSelectView.swift
> +        let totalHorizontalSpacing = (flowLayout.minimumInteritemSpacing * 2) + (28 * 2)
확인했습니다. 1차이가 생각보다 크게 작용하네요 ㅎㅎ

2024-12-14 00:51 UTC, inwoodev commented on Projects/Shared/DesignSystem/Sources/Models/ProfileCharacterType.swift
> +
제 생각에 해당 enum에서 인덱스를 선언하는건 적절하지 않은 것 같아요. 현재는 작성하신 순서대로 각 닉네임 캐릭터가 순서대로 있지만 해당 순서는 프로필 캐릭터가 추가되거나 위치가 수정될 경우 바뀔 수도 있다고 생각해요. 다른 방법으로 접근해 보는건 어떨까요?
p3

2024-12-14 00:51 UTC, inwoodev commented on Projects/Feature/Onboarding/Interface/Sources/Components/Profile/ProfileView.swift
> +
+ 12는 어떤 기준으로 주셨는지 궁금합니다~~

2024-12-14 00:51 UTC, inwoodev commented on Projects/Feature/Onboarding/Interface/Sources/Components/UserInformationView.swift
> +
+ 23도 어떤 기준으로 주셨는지 궁금해요~~

2024-12-14 01:00 UTC, derrickkim0109 commented on Projects/Feature/Onboarding/Interface/Sources/Components/UserInformationView.swift
> +
피그마를 기준으로 적용했습니다.

2024-12-14 01:04 UTC, derrickkim0109 commented on Projects/Feature/Onboarding/Interface/Sources/Components/Profile/ProfileView.swift
> +
이 부분도 동일하게 맞추기 위해 아래와 같이 21 + 23으로 수정하겠습니다

2024-12-14 01:04 UTC, derrickkim0109 commented on Projects/Feature/Onboarding/Interface/Sources/Components/Profile/ProfileView.swift
> +
수정했습니다~!

2024-12-14 01:14 UTC, derrickkim0109 commented on Projects/Shared/DesignSystem/Sources/Models/ProfileCharacterType.swift
> +
말씀하신 내용이 enum 케이스의 순서가 변경될 때마다 사용처에서 해당 변경점에 따라 수정이 필요한 것이 문제가 될 수 있다라는 것을 예상하고 말씀하신 걸까요? 

`index`를 사용하는 목적은 API로 넘어온 Response값의 초기 셋팅값으로서 사용하기 때문에 말씀하신 내용을 제가 이해한게 맞다면 문제가 없다고 생각하는데 혹시 어떤 방식으로 개선하는 것을 말씀하시는 건지 알 수 있을까요?

2024-12-23 12:57 UTC, inwoodev approved these changes
고생하셨습니다. 태현님~~ 저희 한 턴 쉬어가는 기간임에도 불구하고 이렇게 세세한 부분까지 수정 해 주셔서 감사합니다~! 그리고 리뷰와 리뷰 사이에 텀이 조금 길었던 부분 다시한 번 죄송합니다 ㅠㅠ. 머지하셔도 좋습니다.

2024-12-23 12:57 UTC, inwoodev commented on Projects/Coordinator/App/Interface/Sources/Root/CoordinatorInterface.swift
> +                        delegate?.didFinish(childCoordinator: self)
👍👍👍👍

2024-12-23 12:57 UTC, inwoodev commented on Projects/Feature/Onboarding/Interface/Sources/ViewControllers/EditProfileViewController.swift
> +                dismiss(animated: true)
오 저는 요 접근이 더 나은것 같아요~! 이제 불필요하게 index 변수를 ProfileCharacterType에 두지 않아도 되겠네요~. 좋습니다~!!

2024-12-23 12:57 UTC, inwoodev commented on Projects/Feature/MyPage/Interface/Sources/ViewModels/ProfileEditViewModel.swift
> +        let nicknameCondition = nickname?.isEmpty == false && nicknameWordCount <= 10 && userProfile.nickname != nickname && nickname?.containsOnlyAllowedCharacters == true
추후에 저희 `isNotEmpty`와 같은 변수도 util쪽에 만들어서 활용하면 가독성을 더 낫게 할 수 있을 듯 해요~. 무튼 요런 세세한 부분 수정 좋습니다~~

2024-12-23 23:13 UTC, derrickkim0109 commented on Projects/Feature/MyPage/Interface/Sources/ViewModels/ProfileEditViewModel.swift
> +        let nicknameCondition = nickname?.isEmpty == false && nicknameWordCount <= 10 && userProfile.nickname != nickname && nickname?.containsOnlyAllowedCharacters == true
넵 좋습니다~!

2024-12-23 23:14 UTC, merged